name: Run Pump Alarm Bot

# Dit script draait elke 15 minuten
on:
  schedule:
    - cron: '*/15 * * * *'
  # Maakt het ook mogelijk om het handmatig te starten
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest # Draait op een virtuele Linux machine

    steps:
    - name: Check out a copy of the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install all necessary packages
      run: |
        python -m pip install --upgrade pip
        pip install dune-client python-dotenv pandas requests

    - name: Run the Python script
      # We geven de geheimen hier als omgevingsvariabelen mee aan het script
      env:
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py